spring:
  profiles:
    active: dev
elk:
  first:
    account: elk
    pw: elk

query:
  threadPool:
    size: 6

---
spring:
  profiles: dev
  redis:
    host: redis.com
    port: 6379
    database: 0
    pool:
      max-idle: 300
      max-active: 300
      max-wait: 60000

  datasource:
    url: aaa
    username: aaa
    password: aaa
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  profiles: fat
  redis:
    host: redis.com
    port: 6379
    database: 0
    pool:
      max-idle: 300
      max-active: 300
      max-wait: 60000

  datasource:
    url: aaa
    username: aaa
    password: aaa
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


---
spring:
  profiles: alcloud-prod
  redis:
    host: redis.com
    port: 6379
    database: 0
    pool:
      max-idle: 300
      max-active: 300
      max-wait: 60000

  datasource:
    url: aaa
    username: aaa
    password: aaa
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
